<?php

namespace MessageBird\Objects\Conversation;

use MessageBird\Objects\Base;

class ContactIdentifier extends Base
{
    /**
     * A unique ID generated by the MessageBird platform that identifies the
     * contact.
     *
     * @var string
     */
    public $id;

    /**
     * The URL of this contact object.
     *
     * @var string
     */
    public $type;

    /**
     * Display Name
     *
     * @var string
     */
    public $value;

    /**
     * The date and time when this contact was first created in RFC3339
     * format.
     *
     * @var string
     */
    public $createdAt;

    /**
     * Serialize only non empty fields.
     */
    public function jsonSerialize()
    {
        $json = array();

        foreach (get_object_vars($this) as $key => $value) {
            if (!empty($value)) {
                $json[$key] = $value;
            }
        }

        return $json;
    }
}
