<?php

namespace MessageBird\Objects\Conversation;

use MessageBird\Objects\Base;

class InboxContact extends Base
{
    /**
     * A unique ID generated by the MessageBird platform that identifies the
     * contact.
     *
     * @var string
     */
    public $id;

    /**
     * The URL of this contact object.
     *
     * @var string
     */
    public $href;

    /**
     * Display Name
     *
     * @var string
     */
    public $displayName;

    /**
     * @var string
     */
    public $firstName;

    /**
     * @var string
     */
    public $lastName;

    /**
     * An array containing all identifiers details about this contact like phone number and email address.
     *
     * @var array
     */
    public $identifiers;

    /**
     * @var array
     */
    public $languages;

    /**
     * @var string
     */
    public $timezone;

    /**
     * @var string
     */
    public $country;

    /**
     * @var string
     */
    public $avatar;

    /**
     * @var string
     */
    public $gender;

    /**
     * @var array
     */
    public $profiles;

    /**
     * @var object
     */
    public $attributes;

    /**
     * @var string
     */
    public $status;

    /**
     * The date and time when this contact was first created in RFC3339
     * format.
     *
     * @var string
     */
    public $createdAt;

    /**
     * The date and time when this contact was most recently updated in
     * RFC3339 format.
     *
     * @var string
     */
    public $updatedAt;

    /**
     * @var string
     */
    public $email;

    /**
     * @var string
     */
    public $phone;

    /**
     * @param $object
     *
     * @return self
     */
    public function loadFromArray($object)
    {
        parent::loadFromArray($object);

        if (!empty($this->identifiers)) {
            $this->identifiers = (array)$this->identifiers;
        }
        if (!empty($this->languages)) {
            $this->languages = (array)$this->languages;
        }
        if (!empty($this->profiles)) {
            $this->profiles = (array)$this->profiles;
        }

        return $this;
    }
}
